// import Orb5 from "@/components/orb/orb5";
import Orb6 from "@/components/orb/orb6";
import Head from "next/head";


export default function Orbital() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <Orb6 />
      </div>
    </>
  );
}