// import CanvasGallery from "@/components/canvas";
import CanvasGallery3 from "@/components/canvas/index3";
// import IndexGallery from "@/components/index";
// import IndexGallery2 from "@/components/index/index2";
import Head from "next/head";


export default function Index() {
  return (
    <>
      <Head>
        <title>Canvas | Johnny Carrtes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CanvasGallery3 />
      </div>
    </>
  );
}