"use client";

import Head from "next/head";
import HomeSlider4 from "@/components/home_slider/index4";
import HomeSlider5 from "@/components/home_slider/index5";

const images = [
  { src: "/images/image00001.webp", coordinates: "35°18′35″N 24°53′36″E" },
  { src: "/images/image00002.webp", coordinates: "19°28′35″N 24°53′36″W" },
  { src: "/images/image00003.webp", coordinates: "35°68′35″N 24°53′36″E" },
  { src: "/images/image00007.webp", coordinates: "55°88′35″N 14°53′36″W" },
  { src: "/images/image00029.webp", coordinates: "75°78′35″N 57°54′36″E" },
  { src: "/images/image00014.webp", coordinates: "35°48′35″N 24°53′36″E" },
  { src: "/images/image00017.webp", coordinates: "35°17′35″N 12°53′36″E" },
  { src: "/images/image00023.webp", coordinates: "35°10′35″N 24°53′36″E" },
  { src: "/images/image00038.webp", coordinates: "35°18′35″N 11°53′36″E" },
  { src: "/images/image00035.webp", coordinates: "35°18′35″N 24°53′36″W" },
];

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Johnny Carretes | Analog Photography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* Preload de todas las imágenes */}
        {images.map((img, i) => (
          <link key={i} rel="preload" href={img} as="image" />
        ))}
        
      </Head>
      {/* <PageTransition> */}
        {/* <HomeGallery9 images={images}/>  */}
        {/* <div onClick={handleClick}> */}
          {/* <HomeGallery9 src={images[currentIndex]}/> */}
          {/* <div className="revealer"></div> */}
          {/* <Splash2 /> */}
          <HomeSlider4 />
          {/* <HomeGallery11 images={images}/> */}
          {/* <HomeGallery12/> */}
        {/* </div> */}
      {/* </PageTransition> */}
    </>
  );
}
