"use client";

import Head from "next/head";
import HomeSlider5 from "@/components/home_slider/index5";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Johnny Carretes | Analog Photography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        
      </Head>
      <HomeSlider5 />
    </>
  );
}
