import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
// import { useState } from "react";

// import Picture from "../../public/images/image00001.jpeg"
// import Picture2 from "../../public/images/image00023.jpeg"
// import Picture3 from "../../public/images/image00007.jpeg"

// import { images } from "@/components/tools/Images";

// import HomeGallery6 from "@/components/home/index11"; 
// import HomeGallery7 from "@/components/home/index12";
// import HomeGallery10 from "@/components/home/index15";
import HomeGallery11 from "@/components/home/index16";
import HomeGallery12 from "@/components/home/index17";
// import HomeGallery8 from "@/components/home/index13";
// import HomeGallery9 from "@/components/home/index14";
// import HomeGallery7 from "@/components/home/index12";
// en caso de importar homegallery6 enviar image como props al componente, imagenes formato webp

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const images = [
//   "/images/image00001.webp",
//   "/images/image00002.webp",
//   "/images/image00003.webp",
//   "/images/image00007.webp",
//   "/images/image00029.webp",
//   "/images/image00014.webp",
//   "/images/image00017.webp",
//   "/images/image00023.webp",
//   "/images/image00038.webp",
//   "/images/image00035.webp",
  
// ];

const images = [
  { src: "/images/image00001.webp", coordinates: "35°18′35″N 24°53′36″E" },
  { src: "/images/image00002.webp", coordinates: "19°28′35″N 24°53′36″W" },
  { src: "/images/image00003.webp", coordinates: "35°68′35″N 24°53′36″E" },
  { src: "/images/image00007.webp", coordinates: "55°88′35″N 14°53′36″W" },
  { src: "/images/image00029.webp", coordinates: "75°78′35″N 57°54′36″E" },
  { src: "/images/image00014.webp", coordinates: "35°48′35″N 24°53′36″E" },
  { src: "/images/image00017.webp", coordinates: "35°17′35″N 12°53′36″E" },
  { src: "/images/image00023.webp", coordinates: "35°10′35″N 24°53′36″E" },
  { src: "/images/image00038.webp", coordinates: "35°18′35″N 11°53′36″E" },
  { src: "/images/image00035.webp", coordinates: "35°18′35″N 24°53′36″W" },
];

export default function Home() {

  // const images = [Picture, Picture2, Picture3]; // Array de imágenes
  // const [currentIndex, setCurrentIndex] = useState(0); // Estado para controlar la imagen

  // const handleClick = () => {
  //   setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length); // Cambia la imagen al hacer clic
  // };
  
  return (
    <>
      <Head>
        <title>Johnny Carretes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* Preload de todas las imágenes */}
        {images.map((img, i) => (
          <link key={i} rel="preload" href={img} as="image" />
        ))}
        
      </Head>
      {/* <PageTransition> */}
        {/* <HomeGallery9 images={images}/>  */}
        {/* <div onClick={handleClick}> */}
          {/* <HomeGallery9 src={images[currentIndex]}/> */}
          <HomeGallery11 images={images}/>
          {/* <HomeGallery12/> */}
        {/* </div> */}
      {/* </PageTransition> */}
    </>
  );
}
