"use client";

import Head from "next/head";
import WorkMenu10 from "@/components/work/index10";



export default function Work() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <PageTransition> */}
      {/* <div className="revealer"></div> */}
      <WorkMenu10 />
      {/* </PageTransition> */}
    </>
  );
}