// const items = [
//   "Mallorca 2022",
//   "Creta 2021",
//   "Almeria 2022",
//   "Berlin-Tempelhof 2020",
//   "Berlin-Steglitz 2021",
//   "Palermo 2024",
//   "Mallorca 2022",
//   "Creta 2021",
//   "Almeria 2022",
//   "Berlin-Tempelhof 2020",
//   "Berlin-Steglitz 2021",
//   "Palermo 2024",
//   "Mallorca 2022",
//   "Creta 2021",
//   "Almeria 2022",
//   "Berlin-Tempelhof 2020",
//   "Berlin-Steglitz 2021",
//   "Palermo 2024",
//   "Asturias 2021",
//   "Oviedo 2021",
//   "Oviedo 2021",
//   "Oviedo 2021",
//   "Oviedo 2021",
//   "Oviedo 2021",
//   "Oviedo 2021",
//   "Oviedo 2021",
// ]

const items = [
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
]

export default items