const items = [
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Paradise is really Nice", galleryLink: "/work/paradise_is_really_nice" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Paradise is really Nice", galleryLink: "/work/paradise_is_really_nice" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Paradise is really Nice", galleryLink: "/work/paradise_is_really_nice" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Paradise is really Nice", galleryLink: "/work/paradise_is_really_nice" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Johnny Color", galleryLink: "/work/johnny_color" },
  { label: "Paradise is really Nice", galleryLink: "/work/paradise_is_really_nice" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Leak of Dreams", galleryLink: "work/leak_of_dreams" },
  { label: "Costas de Sol", galleryLink: "/work/costas_de_sol" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Johnny de Noche", galleryLink: "/work/johnny_de_noche" },
  { label: "Paradise is really Nice", galleryLink: "/work/paradise_is_really_nice" },
  { label: "Paradise is really Nice", galleryLink: "/work/paradise_is_really_nice" },
]

export default items